version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gnostic123
      POSTGRES_DB: gnostic_iam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - gnostic_network

  # test_gmail_db:
  #   image: postgres:13
  #   container_name: test_gmail_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: gnostic123
  #     POSTGRES_DB: gnostic_mail
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5436:5432"
  #   networks:
  #     - gnostic_network

  iam_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:gnostic123@postgres_db:5432/gnostic_cloud
    depends_on:
      - postgres_db
    networks:
      - gnostic_network

  # mail_service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: pipenv run uvicorn mail.main:app --host 0.0.0.0 --port 8001
  #   environment:
  #     - SQLALCHEMY_DATABASE_URL=postgresql://postgres:gnostic123@postgres_gmail_db:5432/gnostic_mail
  #   depends_on:
  #     - test_gmail_db
  #   networks:
  #     - gnostic_network

  test_service:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - SQLALCHEMY_TEST_DATABASE_URL=postgresql://postgres:gnostic123@postgres_db:5432/test_gnostic
      # - SQLALCHEMY_TEST_DATABASE_URL=postgresql://postgres:gnostic123@postgres_db:5432/test_mail
    depends_on:
      - iam_service
      # - mail_service
    networks:
      - gnostic_network
    command: pipenv run pytest --maxfail=1 --disable-warnings -v

networks:
  gnostic_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
