"""Add bio field to User model

Revision ID: 4774cc94d7b2
Revises: 
Create Date: 2024-10-14 17:33:29.424135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4774cc94d7b2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bio", sa.String(), nullable=True))
    op.alter_column(
        "users",
        "date_of_birth",
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "date_of_birth",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
