"""Updated language table by adding code

Revision ID: 71365c1ff564
Revises: 7e1d36c1a5a1
Create Date: 2024-10-30 18:45:58.575824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71365c1ff564"
down_revision: Union[str, None] = "7e1d36c1a5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("languages", sa.Column("code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languages", "code")
    # ### end Alembic commands ###
