"""Add contacts and contact groups tables and triggers

Revision ID: 7e1d36c1a5a1
Revises: ffd118cdab93
Create Date: 2024-10-29 16:19:45.456750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e1d36c1a5a1"
down_revision: Union[str, None] = "f4385282fe72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("country_of_stay", sa.String(length=100), nullable=True),
        sa.Column("personal_email", sa.String(length=255), nullable=True),
        sa.Column("personal_mobile", sa.String(length=50), nullable=True),
        sa.Column("birthday", sa.DateTime(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_contacts_personal_email"), "contacts", ["personal_email"], unique=True
    )
    op.create_table(
        "groups",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "additional_information",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("related_person", sa.String(length=255), nullable=True),
        sa.Column("who_introduced", sa.String(length=255), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "contact_groups",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "meeting_info",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("place", sa.String(length=255), nullable=True),
        sa.Column("mean", sa.String(length=50), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("google_link", sa.String(length=255), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "social_accounts",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("personal_website", sa.String(length=255), nullable=True),
        sa.Column("linkedin", sa.String(length=255), nullable=True),
        sa.Column("facebook", sa.String(length=255), nullable=True),
        sa.Column("instagram", sa.String(length=255), nullable=True),
        sa.Column("google", sa.String(length=255), nullable=True),
        sa.Column("skype", sa.String(length=255), nullable=True),
        sa.Column("zoom", sa.String(length=255), nullable=True),
        sa.Column("google_meet", sa.String(length=255), nullable=True),
        sa.Column("viber", sa.String(length=255), nullable=True),
        sa.Column("whatsapp", sa.String(length=255), nullable=True),
        sa.Column("x", sa.String(length=255), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.alter_column(
        "role_permissions", "role_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "role_permissions", "permission_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "role_permissions", "permission_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "role_permissions", "role_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_table("social_accounts")
    op.drop_table("meeting_info")
    op.drop_table("contact_groups")
    op.drop_table("additional_information")
    op.drop_table("groups")
    op.drop_index(op.f("ix_contacts_personal_email"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
