"""updated rolepermission table

Revision ID: ffd118cdab93
Revises: 54f12595d08b
Create Date: 2024-10-23 16:46:23.559542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffd118cdab93"
down_revision: Union[str, None] = "54f12595d08b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "role_permissions", "role_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "role_permissions", "permission_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "role_permissions", "permission_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "role_permissions", "role_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
